// Shared point lookup (browser + API route) for the packed ~110m-cell
// bitmasks generated by scripts/generate-*-mask.mjs.

type PackedMask = {
  zoom: number;
  x0: number;
  y0: number;
  scale: number;
  width: number;
  height: number;
  data: string; // base64-packed bits, row-major, LSB first
};

/** Returns a (lat, lng) => boolean test that lazily decodes the mask once. */
export function maskTester(maskDef: PackedMask): (lat: number, lng: number) => boolean {
  let bits: Uint8Array | null = null;

  function mask(): Uint8Array {
    if (!bits) {
      if (typeof Buffer !== "undefined") {
        bits = new Uint8Array(Buffer.from(maskDef.data, "base64"));
      } else {
        const bin = atob(maskDef.data);
        bits = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) bits[i] = bin.charCodeAt(i);
      }
    }
    return bits;
  }

  return (lat: number, lng: number): boolean => {
    const { zoom, x0, y0, scale, width, height } = maskDef;
    const n = 2 ** zoom;
    const px = (((lng + 180) / 360) * n - x0) * 256;
    const mercY = (1 - Math.asinh(Math.tan((lat * Math.PI) / 180)) / Math.PI) / 2;
    const py = (mercY * n - y0) * 256;
    const col = Math.floor(px / scale);
    const row = Math.floor(py / scale);
    if (col < 0 || row < 0 || col >= width || row >= height) return false;
    const idx = row * width + col;
    return (mask()[idx >> 3] & (1 << (idx & 7))) !== 0;
  };
}
