import { PUBLIC_MASK } from "./publicMask";
import { maskTester } from "./maskLookup";

// Shared public-place check (browser + API route). Looks a point up in the
// packed ~110m-cell bitmask generated by scripts/generate-public-mask.mjs,
// built from OSM polygons: parks, gardens, playgrounds, sports grounds,
// beaches, national park, railway and airport land.

/** True when the point sits in a public place (park, ground, station land…) in the PMR. */
export const isPublicPlacePoint = maskTester(PUBLIC_MASK);
