import { WATER_MASK } from "./waterMask";
import { maskTester } from "./maskLookup";

// Shared water check (browser + API route). Looks a point up in the packed
// ~110m-cell bitmask generated by scripts/generate-water-mask.mjs. Cells are
// marked water only when solidly water, so shoreline buildings stay pickable.

/** True when the point sits in open water (river, lake, dam) in the PMR. */
export const isWaterPoint = maskTester(WATER_MASK);
